### ISSUE TITLE
can you please tell me secret of 25gb colab ram notebook? 

### ISSUE THREAD

**Issue by usamaehsan** [satyajitghana/TSAI-DeepVision-EVA4.0#2]

**Comment by satyajitghana** [comment]
i've written it here: https://satyajitghana.github.io/2020/05/upgrade-25gb-colab.html
you just need to open the .ipynb file of colab in notepad

**Comment by usamaehsan** [comment]
thanks man i have got 35gb ram

**Comment by usamaehsan** [comment]
can we increase 12 hour max runtime too?

**Comment by satyajitghana** [comment]
> can we increase 12 hour max runtime too?

that i have no clue, 12 hr is still the limit,

**Comment by satyajitghana** [comment]
> thanks man i have got 35gb ram

35 GB 😲 ? woahhhh

**Comment by usamaehsan** [comment]
> > thanks man i have got 35gb ram
> 
> 35 GB 😲 ? woahhhh

just change runtime type to tpu and you will also get 35gb 😅😂
If you found way of increasing max runtime 
Please let me know
